Add high-level documentation of the methods of customization
CanonicalLtd/cpc-image-customization-examples pull request #3
Opened 2017-03-14 21:01 UTC by OddBloke

2017-03-14 21:17 UTC, rcj4747 requested changes
Spell checking won't always save you ;)

2017-03-14 21:17 UTC, rcj4747 commented on source/index.rst
> +customized to suite the needs and requirements of cloud partners.
s/suite/suit/g

2017-03-14 21:19 UTC, OddBloke commented on source/index.rst
> +customized to suite the needs and requirements of cloud partners.
Fixed.

2017-03-14 21:21 UTC, rcj4747 approved these changes
+1

2017-03-15 07:37 UTC, josvazg approved these changes
LGTM!

2017-03-15 13:39 UTC, merged